### ISSUE TITLE
Are PRs appreciated?

### ISSUE THREAD

**Issue by dcherniv** [twalther/lighthouse-influxdb-grafana#1]
First and foremost, thank you so much for this.
I found this project to be exactly what i needed for monitoring our SPAs.

Do you take PRs? i bumped up lighthouse to latest stable 3.2.1 as well i can contribute a Dockerfile with latest alpine + chromium +lighthouse.
and a helm chart if you want.

**Comment by twalther** [comment]
> First and foremost, thank you so much for this.
> I found this project to be exactly what i needed for monitoring our SPAs.
> 
> Do you take PRs? i bumped up lighthouse to latest stable 3.2.1 as well i can contribute a Dockerfile with latest alpine + chromium +lighthouse.
> and a helm chart if you want.

Hi,
glad you liked it. Yes, PR:s are welcome, I have not used it for a while but keeping it current is great.

**Comment by dcherniv** [comment]
@twalther please see attached ^
